services:
  postgres:
    container_name: pg_booking
    image: postgres:latest
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - booking

volumes:
  postgres_data:

networks:
  booking:
    driver: bridge